### ISSUE TITLE
getPost From DAta Undefined

### ISSUE THREAD

**Issue by ArielPenna** [hidjou/classsed-graphql-mern-apollo#12]
I think the problem might be in the destructoring? according to the error "data " is undefined

![image](https://user-images.githubusercontent.com/42047708/97909037-4e9ff280-1d26-11eb-8244-869258b8599a.png)

**Comment by asinorum** [comment]
I didnt have the exact same error , but maybe it helps, This what ended worked for me for some reason 
`
const {data ={}} = useQuery(FETCH_POST_QUERY, {
        variables: {
            postId
         }
})`

Also replacing `getPost` for  `data.getPost` in the rest of the code

**Comment by likwid23** [comment]
@asinorum That got rid of the error but now it gets stuck on Loading....

it never gets past the (!data.getPost)

**Comment by ArielPenna** [comment]
same to me,

**Comment by ArielPenna** [comment]
So annoying, i've tried everithing tha crossed mi mind, but it stills throw me the data undefined error

**Comment by mariusflorescu** [comment]
Hello @ArielPenna 🚀, have you tried to do the following changes:

From:
```
const {data:{getPost}} = useQuery(FETCH_POST_QUERY,{
    variables: {
      postId
    }
  })
```

To:
```
const {data={}} = useQuery(FETCH_POST_QUERY,{
    variables: {
      postId
    }
  });
const thisPost = data.getPost;
```
+ change everywhere you see **getPost** to **thisPost**. (in the if statement and in the first instruction of the else).

Hope that helped you, let me know if it works!

**Comment by likwid23** [comment]
@mariusflorescu if I remove (!thisPost) I get:

TypeError: Cannot destructure property 'id' of 'thisPost' as it is undefined.

if (thisPost) {
  25 |      postMarkup = <p>Loading post..</p>
  26 |    } else {
> 27 |        const { id, body, createdAt, username, likes, likesCount, comments, commentCount} = thisPost;
     | ^  28 | 
  29 |        postMarkup = (
  30 |            <Grid>

Any ideas are appreciated

**Comment by ArielPenna** [comment]
Thanks @mariusflorescu this just work fine, i've tried it before I think, but didn't work.
Thanks a lot!!

**Comment by ArielPenna** [comment]
@likwid23 try like this, it's working for me

let postMarkup;
  if (!thisPost) {
    postMarkup = <p>Loading post..</p>;
  } else {
    const { id, body, createdAt, username, comments, likes, likeCount, commentCount } = thisPost;

**Comment by mariusflorescu** [comment]
@ArielPenna I'm glad it worked.
You can mark the issue as closed 😁!
