### ISSUE TITLE
'data' is not defined

### ISSUE THREAD

**Issue by mariusflorescu** [hidjou/classsed-graphql-mern-apollo#13]
**- Issue located in:**  _/client/src/pages/Home_
```
const {
    loading,
    data: { getPosts: posts }
  } = useQuery(FETCH_POSTS_QUERY);
```

**-Issue description:** 'data' is not defined (twice) 😢

**-Context:** I think the problem is due to the migration to @apollo/client 3.0 (they've discussed something about some changes regarding loading / data)

**-How I solved it:** : 

```
const{
    loading,
    data={}
  } = useQuery(FETCH_POSTS_QUERY);

const posts = data.getPosts;
```

**Comment by aindriu80** [comment]
I was having this same problem ٩(͡๏̯͡๏)۶
