### ISSUE TITLE
Delete button issue

### ISSUE THREAD

**Issue by ArielPenna** [hidjou/classsed-graphql-mern-apollo#16]
![image](https://user-images.githubusercontent.com/42047708/98488103-ff663000-2205-11eb-8735-2802495d806a.png)
the delete button does not automatically update the render, I have to reload, and in the single post page i doesn't redirec me to home either.
Any Idea?

**Comment by ArielPenna** [comment]
the console.log brings the getposts aray perfectly, but the console throw a "can't read property getPosts of undefined"
 error

**Comment by mariusflorescu** [comment]
Hello @ArielPenna , this might solve your issue:

You should add a poll interval to your useQuery in your Homepage.js, like this:
```
const {loading, data={}} = useQuery(FETCH_POSTS_QUERY,{
    pollInterval: 500,
  });
```

**Comment by ArielPenna** [comment]
Hi, @mariusflorescu thats not working either

**Comment by mariusflorescu** [comment]
Agh sorry, I didn't read the issue carefully enough. 
Try to apply the previous changes + the pollInterval
See the edit.

**Comment by ArielPenna** [comment]
@mariusflorescu thanks, but it didn't solve py issue, the problem is tha when i press de delete button, it actually delet the post but no reload (when in home) or redirect to home (when in singlepost)

**Comment by jamiemetca** [comment]
I had the same issue and fixed it using proxy.modify.
```javascript
      proxy.modify({
        fields: {
          getPosts( existingPostRefs, { readField }) {
            return existingPostRefs.filter( postRef => postId !== readField("id", postRef ));
          }
        }
      })
```

**Comment by Cornstar23** [comment]
Instead of modifying data.getPosts and passing it into proxy.writeQuery, just set a data element directly:
```
proxy.writeQuery({
  query: FETCH_POSTS_QUERY,
  data: { getPosts: data.getPosts.filter((p) => p.id !== postId) },
})
```
