### ISSUE TITLE
Getting error on register form "Cannot read property 'username' of undefined.

### ISSUE THREAD

**Issue by ghost** [hidjou/classsed-graphql-mern-apollo#35]
45 |     name="username"
  46 |     type="text"
  47 |     value={values.username}
> 48 |     error={errors.username ? true : false}
  49 |     onChange={onChange}
  50 | />
  51 | <Form.Input 

so I know 'errors' is undefined.

`    const [addUser, {loading}] = useMutation(REGISTER_USER, {
        update(_, result){
            console.log(result)
            props.history.push('/')
        },
        onError(err){
            console.log(err.graphQLErrors[0].extensions.exception.errors)
            setErrors(err.graphQLErrors[0].extensions.exception.errors)
        },
        variables: values
    })`
this is where we set the error property, right? Is it not setting it correctly? is there an updated way for graphql to set errors?

**Comment by ghost** [comment]
figured it out. Maybe its an update but it should not include "exception"

**Comment by meganlynn21** [comment]
THANK YOU been trying to figure this out lol
