### ISSUE TITLE
cache update

### ISSUE THREAD

**Issue by ArielPenna** [hidjou/classsed-graphql-mern-apollo#9]
In PostForm the code is written so when you make a new post it shold update the apollo cache and render the new post live, 
The cache is updated but I still have to reload the page in order to view the post
![image](https://user-images.githubusercontent.com/42047708/97117096-56d1af80-16e0-11eb-9fcd-e8046b4cbc58.png)
I added some console.logs in order tocheck if the data is correct and everithing is ok

**Comment by asinorum** [comment]
hey, @ArielPenna  Have you been able to solve the problem?

**Comment by ArielPenna** [comment]
Not yet, I can´t find what is wrong, cause actually the localstorage updates just 
fine

**Comment by asinorum** [comment]
Same here, it doesn't give me any error to work with. Everything works fine it just doesn't reload the page.

**Comment by asinorum** [comment]
I still don't understand the problem well, but it seems quite common, for some reason Apollo doesn't notice the change.
I have found this solution (not mine), in case it helps someone:

`const [createPost, {error}] = useMutation (CREATE_POST_MUTATION, {
          variables: values,
          update (proxy, result) {
              const data = proxy.readQuery ({
                  query: FETCH_POSTS_QUERY,
                  variables: values
              });
              data.getPosts = [result.data.createPost, ... data.getPosts];
              proxy.writeQuery ({query: FETCH_POSTS_QUERY, variables: values, data});
              values.body = '';
          }
      });
`

**Comment by ArielPenna** [comment]
It actually works, Thanks a lot!!!

**Comment by Panosmpero** [comment]
> I still don't understand the problem well, but it seems quite common, for some reason Apollo doesn't notice the change.
> I have found this solution (not mine), in case it helps someone:
> 
> `const [createPost, {error}] = useMutation (CREATE_POST_MUTATION, { variables: values, update (proxy, result) { const data = proxy.readQuery ({ query: FETCH_POSTS_QUERY, variables: values }); data.getPosts = [result.data.createPost, ... data.getPosts]; proxy.writeQuery ({query: FETCH_POSTS_QUERY, variables: values, data}); values.body = ''; } }); `

Had same issue when deleting a post, fixed it by doing your method, adding variables to readQuery and writeQuery
`  const [deletePostOrComment] = useMutation(targetMutation, {
    variables: {
      postId,
      commentId,
    },
    update(proxy) {
      setConfirmOpen(false);
      if (!commentId) {
        const data = proxy.readQuery({
          query: FETCH_POSTS_QUERY,
          variables: { postId, commentId }
        });
        data.getPosts = data.getPosts.filter((post) => post.id !== postId);
        proxy.writeQuery({
          query: FETCH_POSTS_QUERY,
          variables: { postId, commentId },
          data,
        });
      }
      if (callback) callback();
    },
    onError(error) {
      console.log(error);
    },
  });`

**Comment by SudhanshuBlaze** [comment]
@asinorum love you man for the fix!!
